package com.bancario.msdirectorio.modelo;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@DynamoDBTable(tableName = "directorio")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Institucion {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "codigoBic")
    private String codigoBic;

    @DynamoDBAttribute(attributeName = "nombre")
    private String nombre;

    @DynamoDBAttribute(attributeName = "urlDestino")
    private String urlDestino;

    @DynamoDBAttribute(attributeName = "llavePublica")
    private String llavePublica;

    @DynamoDBAttribute(attributeName = "estadoOperativo")
    private String estadoOperativo;

    @DynamoDBAttribute(attributeName = "reglasEnrutamiento")
    private List<ReglaEnrutamiento> reglasEnrutamiento;

    @DynamoDBAttribute(attributeName = "interruptorCircuito")
    private InterruptorCircuito interruptorCircuito;

    public enum Estado {
        ONLINE,
        OFFLINE,
        MANT,
        SUSPENDIDO,
        SOLO_RECIBIR
    }
}
